default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitter_development
  username: postgres
  password: 

test:
  <<: *default
  database: twitter_test
  username: postgres
  password: 

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
